params:
      epoch: 300
      batch_size: 8
      lr: 0.001
      timesteps: 500
      num_trajectories: 52
      trajectory_len: 64
      num_samples: 8
      discretization: 0.2

model_params:
      input_dim: 2
      down_dims: [16, 32, 64]
      output_dim: 2
      global_cond_dim: 4
      kernel_size: 3
      n_groups: 1
      scheduler: "linear"
      condition_type: "target_end"

paths:
      pretrain_data_path: ${hydra:runtime.cwd}/../../environment/data/lavaenv
      data_path: ${hydra:runtime.cwd}/../../environment/data/lava_key_sagar_demos
      save_path: ${hydra:runtime.cwd}/../../results/lavaenv
