params:
      epoch: 300
      batch_size: 32
      lr: 0.001
      timesteps: 500
      num_trajectories: 250
      trajectory_len: 64
      num_samples: 8

model_params:
      input_dim: 2
      down_dims: [16, 32, 64]
      output_dim: 2
      global_cond_dim: 4
      kernel_size: 3
      n_groups: 1
      scheduler: "linear"
      condition_type: "start_end"

sampling_params:
      num_samples: 1
      # start_position: [0.0, 0.0]
      # end_position: [8.0, 8.0]
      start_position: None
      end_position: None

paths:
      data_path: ${hydra:runtime.cwd}/../../environment/data/lavaenv
      save_path: ${hydra:runtime.cwd}/../../results/lavaenv
